- hosts: localhost
  become: no
  vars:
    user: wsl
    group: wsl
    php_version: 5.4.16
  tasks:
  - name: Enable add-apt-repository
    block:
    - name: Install apt-file
      apt: name=apt-file state=present
      become: yes
    - name: Install software-properties-common
      apt: name=software-properties-common state=present
      become: yes
  - name: Install settings
    copy: src=wsl.conf dest=/etc/wsl.conf
    become: yes
  - name: Setup task tools
    apt: name=taskwarrior state=present
    become: yes
  - name: Setup jq
    apt: name=jq state=present
    become: yes
  - name: Setup postgres
    apt: name={{ item }} state=present
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
    become: yes
  - name: Setup mcrypt for php
    apt: name={{ item }} state=present
    become: yes
    with_items:
      - mcrypt
      - php-mcrypt
      - php-dev
      - libmcrypt-dev
      - gcc
      - make
      - autoconf
      - libc-dev
      - pkg-config
  roles:
    - phpenv
    - mysql
