#
# Install phpenv
#

- name: check phpenv installed
  stat: path=~/.phpenv
  register: phpenv

- block:
  - name: install.download
    get_url: url=https://raw.github.com/CHH/phpenv/master/bin/phpenv-install.sh dest=/tmp/phpenv-install.sh

  - name: install.chmod
    file: path=/tmp/phpenv-install.sh mode=0744 owner={{ user }} group={{ group }}

  - name: install.install
    shell: /tmp/phpenv-install.sh

  - name: install.php-build
    git: repo=git://github.com/CHH/php-build.git dest=/home/{{ user }}/.phpenv/plugins/php-build update=no accept_hostkey=yes

  when: not phpenv.stat.exists

#
# Setup Extension
#
- name: copy default_configure_options
  copy: src=default_configure_options dest=/home/{{ user }}/.phpenv/plugins/php-build/share/php-build/default_configure_options mode=0666 owner={{ user }} group={{ group }}

- block:
  - name: copy bash fragment
    copy: src=200_phpenv.sh dest=/home/{{ user }}/.bash.d/ mode=0744 owner={{ user }} group={{ group }}

  - name: rehash
    shell: phpenv rehash

  - name: check whether a specific version of php is installed
    shell: phpenv versions | grep {{ php_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d ' '
    register: phpenv_php_version

  - name: install php
    shell: phpenv install {{ php_version }}

  - name: set plenv global
    shell: phpenv global {{ php_version }}
    when: phpenv_php_version.stdout != php_version

  when: not phpenv.stat.exists
